### ISSUE TITLE
cannot find the adns lib while link

### ISSUE THREAD

**Issue by huahandsome** [Drahflow/crawler#1]
Hello author,

Today I am going to study the crawler based on your code. But after I downloaded and built (both under Windows with cygwin & Ubuntu 16.04), it said that it failed to locate the library adns.

The log is attached below:

carl@ubuntu:~/myCrawler/crawler$ make
g++ -std=c++11 -W -Wall -Wextra -Wno-missing-field-initializers -Werror -O4 -ggdb -pg -fprofile-arcs -ftest-coverage -c -o tests.o tests.c++
g++ -std=c++11 -W -Wall -Wextra -Wno-missing-field-initializers -Werror -O4 -ggdb -pg -fprofile-arcs -ftest-coverage -ladns -o tests tests.o
/usr/bin/ld: cannot find -ladns
collect2: error: ld returned 1 exit status
Makefile:8: recipe for target 'tests' failed
make: *** [tests] Error 1

Would you please give me some clues on this?

Many thanks,

My e-mail: huahandsome@gmail.com

Carl.

**Comment by huahandsome** [comment]
An update for above comments:

After installing the libadns in Ubuntu ( sudo apt-get install libadns1 ), I get rid of the error, but another error comes:

carl@ubuntu:~/myCrawler/crawler$ make
g++ -std=c++11 -W -Wall -Wextra -Wno-missing-field-initializers -Werror -O4 -ggdb -pg -fprofile-arcs -ftest-coverage -ladns -o tests tests.o
g++ -std=c++11 -W -Wall -Wextra -Wno-missing-field-initializers -Werror -O4 -ggdb -pg -fprofile-arcs -ftest-coverage -c -o main.o main.c++
g++ -std=c++11 -W -Wall -Wextra -Wno-missing-field-initializers -Werror -O4 -ggdb -pg -fprofile-arcs -ftest-coverage -ladns -o crawler main.o
main.o: In function `main':
/home/carl/myCrawler/crawler/main.c++:87: undefined reference to `adns_init'
/home/carl/myCrawler/crawler/main.c++:143: undefined reference to `adns_check'
/home/carl/myCrawler/crawler/main.c++:132: undefined reference to `adns_submit'
/home/carl/myCrawler/crawler/main.c++:231: undefined reference to `adns_finish'
collect2: error: ld returned 1 exit status
Makefile:11: recipe for target 'crawler' failed
make: *** [crawler] Error 1

It looks like the library I used has some different with what you used.

thanks,

Carl.

**Comment by huahandsome** [comment]
Hello,

I get the library version information shown as below:

carl@ubuntu:~/myCrawler/crawler$ ldd -v /usr/lib/libadns.so.1.5 
	linux-vdso.so.1 =>  (0x00007ffc2ed8f000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f3269a24000)
	/lib64/ld-linux-x86-64.so.2 (0x000055adf5b27000)

	Version information:
	/usr/lib/libadns.so.1.5:
		libc.so.6 (GLIBC_2.14) => /lib/x86_64-linux-gnu/libc.so.6
		libc.so.6 (GLIBC_2.16) => /lib/x86_64-linux-gnu/libc.so.6
		libc.so.6 (GLIBC_2.15) => /lib/x86_64-linux-gnu/libc.so.6
		libc.so.6 (GLIBC_2.4) => /lib/x86_64-linux-gnu/libc.so.6
		libc.so.6 (GLIBC_2.3.4) => /lib/x86_64-linux-gnu/libc.so.6
		libc.so.6 (GLIBC_2.2.5) => /lib/x86_64-linux-gnu/libc.so.6
	/lib/x86_64-linux-gnu/libc.so.6:
		ld-linux-x86-64.so.2 (GLIBC_2.3) => /lib64/ld-linux-x86-64.so.2
		ld-linux-x86-64.so.2 (GLIBC_PRIVATE) => /lib64/ld-linux-x86-64.so.2

thanks,

Carl.

**Comment by Drahflow** [comment]
Apparently g++ got interested in the order of linked objects at some point in time.

For completeness sake, this issue should be fixed with 216bcf303e4563fd4f6ecac1b2f0ef1739097eb6
